trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: sudo apt-get install clang-tidy
  displayName: 'install clang-tidy'

- script: |
    mkdir build
    cd build
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    make
  displayName: 'build'

- script: clang-tidy .
  displayName: 'clang-tidy'