trigger:
- master

pool:
  vmImage: 'ubuntu-disco'

steps:

- script: azure/prepare.sh
  displayName: 'prepare'

- script: |
    mkdir build
    cd build
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    make
  displayName: 'build'

- script: |
    cd build
    wget https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py
    python run-clang-tidy.py
  displayName: 'clang-tidy'