trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install clang-format
    wget https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py
  displayName: 'install'

- script: python run-clang-format.py -r src/ test/
  displayName: 'clang-format'
