trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: apt install clang-format
  displayName: 'install'

- script: clang-format --format=Google src/*.cpp src/*.h
  displayName: 'build'
