name: aur

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  push-aur:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup key
      env:
        sshkey: ${{ secrets.AUR_PRIVATE_KEY }}
      run: |
        set -x
        echo $sshkey > ~/.ssh/id_rsa
        wc -l ~/.ssh/id_rsa
