name: aur

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  push-aur:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup key
      env:
        sshkey: ${{ secrets.AUR_PRIVATE_KEY }}
      run: |
        set -eux
        mkdir -p ~/.ssh/
        echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
        echo $sshkey >> ~/.ssh/id_rsa
        echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa
        wc -l ~/.ssh/id_rsa
        chmod -R 700 ~/.ssh/id_rsa
        ssh-keygen -p -m PEM -f ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub
        cat << EOF | tee ~/.ssh/config
        Host aur.archlinux.org
          IdentityFile ~/.ssh/id_rsa
          User aur
        EOF
    - name: update PKGBUILD
      run: |
        set -eux
        rev=$(date +%s)
        cd packaging/archlinux
        source PKGBUILD
        echo $rev
        sed -i "s/pkgver=$pkgver/pkgver=$pkgver.$rev/g" PKGBUILD
        cat PKGBUILD
    - name: prepare srcinfo
      run: |
        docker run -v $PWD:/workspace zasdfgbnm/archlinux-yaourt bash -c '
          set -eux
          cd /workspace/packaging/archlinux
          makepkg --printsrcinfo | sudo tee .SRCINFO
        '
    - name: push
      run: |
        set -eux
        git clone ssh://aur@aur.archlinux.org/tcg-git.git
        cd tcg-git
        rm -rf *
        cp ../packaging/archlinux/* .
        ls
