name: aur

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  push-aur:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup key
      env:
        sshkey: ${{ secrets.AUR_PRIVATE_KEY }}
      run: |
        set -eux
        echo "-----BEGIN OPENSSH PRIVATE KEY-----" > /tmp/id_rsa
        echo $sshkey >> /tmp/id_rsa
        echo "-----END OPENSSH PRIVATE KEY-----" >> /tmp/id_rsa
        wc -l /tmp/id_rsa
    - name: update PKGBUILD
      run: |
        set -eux
        rev=$(date +%s)
        cd packaging/archlinux
        source PKGBUILD
        echo $rev
        sed -i "s/pkgver=$pkgver/pkgver=$pkgver.$rev/g" PKGBUILD
        cat PKGBUILD
