name: debug

on:
  pull_request:

jobs:

  archlinux-pkg:
    runs-on: ubuntu-20.04
    container: zasdfgbnm/archlinux-yaourt
    steps:
    - name: build tcg
      run: |
        set -eux
        sudo chown user .
        yaourt -G tcg
        ls
        cd tcg
        makepkg -s --noconfirm
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: archlinux-pkg
        path: tcg/*.pkg.tar.zst
        retention-days: 1

  # copy-pasted from ubuntu.yml
  debian-pkg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        set -eux
        ci/add-debian-sid.sh
        sudo apt-get install -y "libboost-filesystem1.71-dev" "libfmt-dev=7.*" "libspdlog-dev=1:*" libseccomp-dev xonsh
    - name: Compile
      env:
        CC:   gcc-10
        CXX:  g++-10
      run: |
        set -eux
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr ..
        make -j
    - name: Package
      run: |
        set -eux
        cd build
        cpack
    - uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: build/*.deb
        retention-days: 5