name: deploy

on:
  push:
    branches:
      - master

jobs:

  archlinux-aur:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup key
      env:
        sshkey: ${{ secrets.AUR_PRIVATE_KEY }}
      run: ci/setup-ssh-git.sh
    - name: prepare
      run: |
        set -eux
        cd packaging/archlinux
        ./prepare.sh
    - name: push
      run: |
        set -eux
        cd packaging/archlinux
        ./push.sh

  validate-aur:
    runs-on: ubuntu-20.04
    container: zasdfgbnm/archlinux-yaourt
    needs:
      - archlinux-aur
    steps:
    - name: validate tcg
      run: |
        set -eux
        yaourt -Sy --noconfirm tcg
        sudo pacman -Rns --noconfirm tcg
    - name: validate tcg-git
      run: |
        set -eux
        yaourt -Sy --noconfirm tcg-git
        sudo pacman -Rns --noconfirm tcg-git

  xonsh-pypi:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: |
        set -eux
        python -m pip install --upgrade pip
        pip install twine wheel xonsh
    - name: build and upload
      run: |
        set -eux
        cd shells/xonsh
        rm -rf dist/*
        python setup.py sdist bdist_wheel
        twine upload -u zasdfgbnm-bot -p ${{secrets.ZASDFGBNM_BOT_PYPI_PASSWORD}} dist/*
