name: ubuntu

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  debian-pkg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        set -eux
        ci/add-debian-sid.sh
        sudo apt-get install -y "libboost-filesystem1.71-dev" "libfmt-dev=7.*" "libspdlog-dev=1:*" libseccomp-dev xonsh
    - name: Compile
      env:
        CC:   gcc-10
        CXX:  g++-10
      run: |
        set -eux
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr ..
        make -j
    - name: Package
      run: |
        set -eux
        cd build
        cpack
        apt-get download libfmt7 libspdlog1
    - uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: build/*.deb
        retention-days: 5

  limited-tests:  # run tests that does not require VM (i.e. those that don't uses cgroup v2 controllers)
    runs-on: ubuntu-20.04
    needs:
      - debian-pkg
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: deb-package
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Setup environment
      run: ｜
        set -eux
        sudo apt install -y ./*.deb
        tcg
    - name: Run tests on cgroup hybrid
      continue-on-error: false
      run: |
        set -eux
        pip install xonsh pytest wheel pytest-json-report pytest-timeout
        export TCG_LOG_LEVEL=debug
        pytest --json-report --json-report-file=test_result.json --timeout=60 -v
    - uses: actions/upload-artifact@v2
      with:
        name: test-result
        path: test_result.json
        retention-days: 1
    - name: Show system log
      run: |
        sudo dmesg
        journalctl --no-pager

  push-package:
    runs-on: ubuntu-20.04
    needs:
      - debian-pkg
      # - limited-tests
    # if: github.event_name == 'push'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: deb-package
    - name: Prepare
      run: |
        set -eux
        # install aptly
        sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
        sudo add-apt-repository "deb http://repo.aptly.info/ nightly main"
        sudo apt-get update
        sudo apt-get install aptly

        # create repository
        aptly repo create -component=main tcg
        aptly repo add tcg ./*.deb
        aptly repo show -with-packages tcg
        aptly publish repo -distribution=all -skip-signing tcg

        # prepare to push
        cp -r ~/.aptly/public ./deb
        tree -H '.' --noreport --charset utf-8 > index.html
        ls
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: deb
        destination_dir: deb

  validate-repo:
    runs-on: ubuntu-20.04
    needs:
      - push-package
    steps:
    - name: Validate deploy
      run: |
        echo "deb [trusted=yes check-date=no] https://zasdfgbnm.github.io/tcg/deb/ all main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y tcg
        tcg
