name: ubuntu

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  debian-pkg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        set -eux
        ci/add-debian-sid.sh
        sudo apt-get install -y "libboost-filesystem1.71-dev" "libfmt-dev=7.*" "libspdlog-dev=1:*" libseccomp-dev xonsh
    - name: Compile
      env:
        CC:   gcc-10
        CXX:  g++-10
      run: |
        set -eux
        ver=$(python shells/xonsh/setup.py --version)
        mkdir build
        cd build
        cmake -DVERSION=${ver} ..
        make -j
    - name: Package
      run: |
        set -eux
        cd packaging/debian
        sudo ./build.xsh
    - uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: packaging/debian/*.deb
        retention-days: 5

  limited-tests:  # run tests that does not require VM (i.e. those that don't uses cgroup v2 controllers)
    runs-on: ubuntu-20.04
    needs:
      - debian-pkg
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: deb-package
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Setup environment
      run: |
        set -eux
        ci/add-debian-sid.sh
        sudo apt install -y ./tcg*.deb
    - name: Run tests on cgroup hybrid
      continue-on-error: true
      run: |
        set -eux
        pip install xonsh pytest wheel pytest-json-report pytest-timeout
        export TCG_LOG_LEVEL=debug
        pytest --json-report --json-report-file=test_result.json --timeout=60 -v
    - uses: actions/upload-artifact@v2
      with:
        name: test-result
        path: test_result.json
        retention-days: 1
    - name: Show system log
      run: |
        sudo dmesg
        journalctl --no-pager
